### ISSUE TITLE
Run Interface on AlienGo

### ISSUE THREAD

**Issue by itaouil** [graiola/wolf_aliengo_interface#1]
Ciao Gennaro,

I was planning to attempt to test the WOLF controller (tomorrow/this week) with the AlienGo we have in the lab :).

I will have to write the node that publishes the **joint_states** topic as the **tf_tree** is not published by default (as I suppose the WBC requires the tree to work?), but afterwards, everything should be ready for testing.

From my quick glance at the code, you already wrote all that is needed, including setting the **low_level** mode, as the controller publishes **joint_torques**, and the whole abstraction to read the incoming sensory data.

**Questions**:

1) All I have to do is launch the **aliengo_ros_node.cpp** to test?
2) Over which topic should I send the reference velocity command? Is it still a joy command type?
3) Is there something specific that should I know or do before testing?
4) Are there interesting data that you would like me to log to improve/debug the controller?
5) Should I maybe modify the **params** of the robot before testing?

I will make sure to take some videos :).
 
Thanks for making this interface available as well :)

**Comment by graiola** [comment]
Hi @itaouil, to run the code on the robot you can do the following:

1) launch the wb_controller 
2) rosrun the aliengo_ros_node

The joint_states and the tf tree should be available when you launch wb_controller.

The params you have are tuned for simulation, I would suggest to lower the PID values and the other gains.

Unfortunately we had some preliminary tests with our aliengo but then we had to stop the experiments because of time constraints, so you would be the first one to really try it on the hw. For this reason I would suggest you to use very very low gains and increase them slowly to avoid instabilities.

Also, we need to define a proper startup procedure because we assume that the robot starts in the air but I don't know if this is going to be the case for you.

If you have a ps3 or xbox joypad you can use either of them, I think this would simplify the tests.

Let me know what you think :)

**Comment by itaouil** [comment]
Ok I got it now on how to run it :).

Does the joystick need to be connected with Bluetooth or it can also work if it is usb connected to the main PC?

We have a holder for the robot that I could use, so starting in the air should not be a problem and I would leave it attached to this holder at all times in case something crazy happens :).

Regarding the gains I will play with the parameters using the rqt interface starting with low ones as you suggested then :).

One more thing. At which frequency are the torques sent? 1KHz or 500Hz or does this depend on the SDK used?

**Comment by graiola** [comment]
Usually I connect my joypad to the pilot pc where I launch the wb_controller and the hardware interface, I think it doesn't matter if bluetooth or wired...

The torques should be sent at 1Khz but this depends a lot on the computer specs... a way to check if the controller is running at 1Khz, is to run `rostopic hz` on a topic published by the wb_controller.

**Comment by graiola** [comment]
Also, I suggest you to take the last debians because I added a flag to use the IMU's velocities wrt the base of the robot, which is the case for Aliengo.

I am thinking that it could be useful to have a slider going from 0 to 1 to increase the PID gains gradually at the startup, so that you can start in the air with the robot and gradually increase the PID values until it is stiff enough to be placed on the ground. What do you think?

**Comment by itaouil** [comment]
> Usually I connect my joypad to the pilot pc where I launch the wb_controller and the hardware interface, I think it doesn't matter if bluetooth or wired...
> 
> The torques should be sent at 1Khz but this depends a lot on the computer specs... a way to check if the controller is running at 1Khz, is to run `rostopic hz` on a topic published by the wb_controller.

Ok got it.

We have a mini intel PC as the on board computer so it should be enough hopefully.

**Comment by itaouil** [comment]
> Also, I suggest you to take the last debians because I added a flag to use the IMU's velocities wrt the base of the robot, which is the case for Aliengo.
> 
> I am thinking that it could be useful to have a slider going from 0 to 1 to increase the PID gains gradually at the startup, so that you can start in the air with the robot and gradually increase the PID values until it is stiff enough to be placed on the ground. What do you think?

What are the IMU velocities w.r.t in simulation?

Yes good idea. Aren't the sliders already available in the rqt parameter server? I thought I saw them... Or maybe they are only defined in the params file but not dynamically changeable yet?

**Comment by graiola** [comment]
> > Usually I connect my joypad to the pilot pc where I launch the wb_controller and the hardware interface, I think it doesn't matter if bluetooth or wired...
> > The torques should be sent at 1Khz but this depends a lot on the computer specs... a way to check if the controller is running at 1Khz, is to run `rostopic hz` on a topic published by the wb_controller.
> 
> Ok got it.
> 
> We have a mini intel PC as the on board computer so it should be enough hopefully.

I used a mini intel pc on aliengo as well but I found out that it was too slow, so I started using my personal gaming laptop and it solved the issue. The hardware interface works as an UDP connection to the robot, so you don't need to run the code directly on the robot but you can run everything on a more powerful pc.

**Comment by graiola** [comment]
> > Also, I suggest you to take the last debians because I added a flag to use the IMU's velocities wrt the base of the robot, which is the case for Aliengo.
> > I am thinking that it could be useful to have a slider going from 0 to 1 to increase the PID gains gradually at the startup, so that you can start in the air with the robot and gradually increase the PID values until it is stiff enough to be placed on the ground. What do you think?
> 
> What are the IMU velocities w.r.t in simulation?
> 
> Yes good idea. Aren't the sliders already available in the rqt parameter server? I thought I saw them... Or maybe they are only defined in the params file but not dynamically changeable yet?

The floating base angular velocities needs to be defined wrt world frame to be able to update the virtual chains.
But as we know, IMU angular velocities are usually defined wrt the base/trunk, so, inside the code I rotate the velocities from base to world to be able to update correctly the floating base state.

Now, regarding the simulation, it depends if you are using the `ground_truth` or the `imu_magnetometer`. In the first case, the angular velocities are taken directly from Gazebo which means that they are defined directly wrt the world, so no rotation is needed. In the second case we have to differentiate if you are using the IMU ROS plugin or not. If you launch the controller with the arg `sensors:=true` you activate the plugin which means that the angular velocities are defined wrt the base, otherwise I take the velocities from Gazebo (that as we said, are defined wrt world) and rotate them to be defined wrt the base so that the behavior from the controller side is consistent when using the IMU interface.

On the robot instead, the angular velocities are always defined wrt the base, in fact I have to do the inverse of what I just told you, see [here](https://github.com/graiola/wolf_aliengo_interface/blob/master/src/aliengo_robot_hw.cpp#L99-L124).

Unfortunately it is confusing because the `ground_truth` interface should not exists, but I kept it for testing :)

**Comment by graiola** [comment]
> Yes good idea. Aren't the sliders already available in the rqt parameter server? I thought I saw them... Or maybe they are only defined in the params file but not dynamically changeable yet?

you can use them to tune the gains of the tasks but not for the PIDs...

**Comment by itaouil** [comment]
Sorry for the delay in the response/update.

I should receive a more powerful laptop PC for work next week and will get to it :)

I will look into the PID slider this weekend hopefully so it is ready for next week :).

**Comment by itaouil** [comment]
Hi @graiola,

It seems that I will only be able to test on the real robot only next year maybe...

I will close this issue for the moment and re-open it when it is needed next year :).

Thanks for the support on this nonetheless!
